pipeline:

  install:
    image: composer
    pull: true
    commands: [ 
      'composer install --prefer-dist' 
    ]

  test:
    image: php:7.2-fpm
    environment:
      - REDIS_HOST=redis
    commands: [
      'sleep 15',
      'bin/phpunit'
    ]    

  publish:
    image: byrnedo/alpine-curl
    commands: [ 'curl -XPOST -H"content-type:application/json" "https://packagist.org/api/update-package?username=andrewmclagan&apiToken=2cmy6xog4hs0kogk4ccg" -d''{"repository":{"url":"https://github.com/ethical-jobs/quantify"}}''' ]
    when:
      status: success
      event: tag

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments

services:
  redis:
    image: redis       
