pipeline:

  install:
    image: ethicaljobs/composer-prestissimo
    commands: [ 
      'composer install --prefer-dist' 
    ]

  test:
    image: php:7.3-fpm
    environment:
      - REDIS_HOST=redis
    commands: [
      'bin/phpunit'
    ]    

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments

services:
  redis:
    image: redis       

