version: '2'
services:       

  redis:
    image: redis
    ports: [ '6379:6379' ]

  php: 
    image: php:7.2-fpm
    volumes: [ './:/var/www' ]  
    working_dir: /var/www
    links: [ redis ]   
    environment:
      - REDIS_HOST=redis
    